Computing Eigenvalues

In [66]:
import numpy as np

In [67]:
A=np.array([[4,2],[2,3]])
print (A)

[[4 2]
 [2 3]]


In [68]:
eigenvalues,eigenvectors=np.linalg.eig(A)
print (eigenvalues)
print (eigenvectors)

[5.56155281 1.43844719]
[[ 0.78820544 -0.61541221]
 [ 0.61541221  0.78820544]]


In [69]:
for i in range (len(eigenvalues)):
  v=eigenvectors[:,i]
  lhs=A@v
  rhs=eigenvalues[i]*v
  error=np.linalg.norm(lhs-rhs)
  print (
      f"\n Eigenvalues {eigenvalues[i]:4f}"
      f"||Av-v||={error:2e}"
  )
  print (
      f"\n Trace:{np.trace(A):4f}|"
      f"Sum of eigenvalues:{np.sum(eigenvalues):4f}"
  )
  print (
      f"\n Determiant:{np.linalg.det(A):4f}|"
      f"Product of eigenvalues:{np.prod(eigenvalues):4f}"
  )


 Eigenvalues 5.561553||Av-v||=9.930137e-16

 Trace:7.000000|Sum of eigenvalues:7.000000

 Determiant:8.000000|Product of eigenvalues:8.000000

 Eigenvalues 1.438447||Av-v||=0.000000e+00

 Trace:7.000000|Sum of eigenvalues:7.000000

 Determiant:8.000000|Product of eigenvalues:8.000000


Eigendecomposition

In [70]:
V=eigenvectors
Lambda=np.diag(eigenvalues)
A_reconstructed = V @ Lambda @ np.linalg.inv(V)
print("General reconstruction error :", np.linalg.norm(A - A_reconstructed))

A_reconstructed_sym = V @ Lambda @ V.T
print("Symmetric reconstruction error :", np.linalg.norm(A - A_reconstructed_sym))

General reconstruction error : 1.0877919644084146e-15
Symmetric reconstruction error : 4.440892098500626e-16


Power Iteration

In [71]:
def power_iteration(A, num_iters=100):
    n = A.shape[0]
    v = np.random.randn(n)
    v = v / np.linalg.norm(v)

    for _ in range(num_iters):
        v = A @ v
        v = v / np.linalg.norm(v)

    eigenvalue = (v.T @ A @ v) / (v.T @ v)
    return eigenvalue, v

eigval, eigvec = power_iteration(A)
print(f"Power iteration = {eigval:.4f}")
dominant_idx = np.argmax(np.abs(eigenvalues))
print(f"Numpy result = {eigenvalues[dominant_idx]:.4f}")

Power iteration = 5.5616
Numpy result = 5.5616


Full and Thin SVD

In [72]:
import numpy as np

np.random.seed(42)
A = np.random.randn(5, 3)
print("Matrix A (5x3):")
print(A)

Matrix A (5x3):
[[ 0.49671415 -0.1382643   0.64768854]
 [ 1.52302986 -0.23415337 -0.23413696]
 [ 1.57921282  0.76743473 -0.46947439]
 [ 0.54256004 -0.46341769 -0.46572975]
 [ 0.24196227 -1.91328024 -1.72491783]]


In [73]:
U, S, Vt = np.linalg.svd(A, full_matrices=True)

print(f"\nU shape: {U.shape} | S shape: {S.shape} | Vt shape: {Vt.shape}")
print(f"\nSingular values: {S}")

Sigma = np.zeros_like(A, dtype=float)
Sigma[:len(S), :len(S)] = np.diag(S)
A_reconstructed = U @ Sigma @ Vt
print(f"\nReconstruction error: {np.linalg.norm(A - A_reconstructed):.2e}")


U_thin, S_thin, Vt_thin = np.linalg.svd(A, full_matrices=False)
print(f"\nThin U shape: {U_thin.shape}")
A_reconstructed_thin = U_thin @ np.diag(S_thin) @ Vt_thin
print(f"Thin reconstruction error: {np.linalg.norm(A - A_reconstructed_thin):.2e}")



U shape: (5, 5) | S shape: (3,) | Vt shape: (3, 3)

Singular values: [2.7823678  2.30281077 0.89103186]

Reconstruction error: 1.62e-15

Thin U shape: (5, 3)
Thin reconstruction error: 1.62e-15
